### ISSUE TITLE
error running example files

### ISSUE THREAD

**Issue by Mawul4j** [ustunb/risk-slim#1]
Hi, 
Thanks for sharing your code. I tried to run the _**ex_01_quickstart.py**_ file but it gave me the following error. 
![capture](https://user-images.githubusercontent.com/16046768/28372309-5d0a9180-6c6d-11e7-9afd-0ee1c43abd15.PNG)

Do you know of any fix for this? I have tried to dig into the code but found nothing that could work.
Thanks.

**Comment by ustunb** [comment]
Hmm yes this weird. 

Yes this is the first time I'm seeing this bug. I suspect it's because you're using Python 3 instead of Python 2.7 (though it could be something else since I've only tested the code on UNIX environments with Python 2.7). Either way, can you check and confirm?

If you're using Python 3, try switching to Python 2 in Anaconda and see if that addresses the problem. There are some instructions on how to do this at [https://conda.io/docs/py2or3.html](https://conda.io/docs/py2or3.html)

**Comment by Mawul4j** [comment]
Hi, 
Thanks a lot for the help. I was able to fix it. It had to do with the data type stored for the data dimensions. It was 'long' while the program does not allow for it so I just added it and it worked.

Thanks again.
