### ISSUE TITLE
Nested 5-fold Cross-validation and performance metric?

### ISSUE THREAD

**Issue by juanhu96** [ustunb/risk-slim#18]
Hi Berk,

I am trying to run the RiskSLIM model for my own dataset and am trying to do a nested k-fold cross-validation (same as what you've done in the paper). However, I wasn't able to find the code where nested cross-validation is being handled. The only thing I found related is the fold_csv_file in the utils.py, but to me it seems like it is just regular k-fold cross-validation instead of nested validation. I am also thinking of doing the cross-validation based on different performance metrics (accuracy, AUC, etc.) and am not sure where could I change those things.

Thanks!

**Comment by ustunb** [comment]
Hi.

The code here is not really meant to support nested-CV since there are too
many variations and since it's duplicating functionality that's
already implemented in other packages.

The code that's already here for CV is mainly meant to help you reproduce
the results in the paper. In that case, I didn't have to do run nested-CV
for risk-slim since there is no "parameter tuning" once the model size is
fixed.

I recommend that you implement a script. You can use the functions in this
repository to fit a risk slim model for a given X, y.

Hope this helps!

**Comment by juanhu96** [comment]
Thank you so much!
