### ISSUE TITLE
Error to pickle.load(results_files)

### ISSUE THREAD

**Issue by animalbrother** [ustunb/risk-slim#3]
Hello,
Thanks for your sharing code. I successfully run "bash batch/job_template.sh" as instructed and got the "breastcancer_fold_0_results.p" file, but failed to run "results = pickle.load(infile)"  and it gave me the following error.
![type_error](https://user-images.githubusercontent.com/33387195/40877905-e798cf0e-66ba-11e8-88db-50e28633d13c.jpg)

I wonder how to deal with this error, looking forward for your reply! Thanks!

**Comment by ustunb** [comment]
Thanks for letting me know. It looks like there was a bug when saving the coefficient set object. I have changed the code so that it can no longer be saved anymore. This should resolve the issue. 

Just FYI, the job_template.sh file is really for batch computing (e.g., on the cloud / EC2). If you're using it on your computer, I'd advise working off one of the scripts in examples/
